### ISSUE TITLE
Does it support bullets?

### ISSUE THREAD

**Issue by lokeshh** [clearnote01/notes_syntax_vim#1]
I often do the following while writing notes:

These are the things I require
\- duck
\- pond
\- circle
\- sun

**Comment by clearnote01** [comment]
Okay, I'll add it. Do you recommend a particular color to go with it?

**Comment by clearnote01** [comment]
Closing this. Added support for "-" typing.

**Comment by lokeshh** [comment]
Can you suggest some good tutorial to learn vim?

**Comment by clearnote01** [comment]
If you have vim installed, type the command vimtutor for an interactive guide to vim. I found it really really useful.

**Comment by lokeshh** [comment]
I have tried that tutorial couple of times but left in the middle.
